#!/bin/bash

set -e -x

export GOPATH=$PWD/go_workspace
export PATH=$GOPATH/bin:$PATH

go get github.com/tools/godep

pushd ${GOPATH}/src/github.com/comcast/cf-scaler-service
  godep go test ./... -v -race
popd
